### ISSUE TITLE
Incorrect buffer size for encoded or decoded data

### ISSUE THREAD

**Issue by rexcheung21** [mattn/mruby-base64#6]
Valgrind reported invalid write error when encoding one-byte data. In the ``base64_encode()`` function, length of output data is ``(3 * in_len) + 1``. If ``in_len`` is 1, size of output data becomes 4, which is 1 less than needed. One formula to calculate minimal buffer size is ``(in_len + 2) / 3 * 4 + 1``.
In contrast, size of decoded data is way larger than necessary. It can be changed to ``(in_len + 3) / 4 * 3 + 1``.

**Comment by mattn** [comment]
Thanks. Could you please send PR?

**Comment by rexcheung21** [comment]
I have created PR:
https://github.com/mattn/mruby-base64/pull/7

**Comment by rexcheung21** [comment]
As the fix is merged, I would like to close the issue.
